services:
  streamlit:
    build:
        context: ./streamlit
        dockerfile: Dockerfile
    container_name: streamlit.latest
    environment:
        PORT: 8501
    ports:
      - '8501:8501'
    restart: "no"


