version: '3'

services:
  streamlit:
    build:
      context: ./streamlit

    container_name: streamlit.latest

    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    depends_on:
      - fastapi
    restart: "no"

  fastapi:
    build:
      context: ./api
    container_name: fastapi.latest

    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: "no"

